# Generated by Django 6.0.1 on 2026-02-03 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_pelicula_imagen_pelicula_sinopsis'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='directores/'),
        ),
    ]
